#!/usr/bin/sh

get_values() {
		capacity=$(grep 'POWER_SUPPLY_CAPACITY=' /sys/class/power_supply/$bat/uevent | cut -d= -f2)
	    full=$(grep 'POWER_SUPPLY_ENERGY_FULL=' /sys/class/power_supply/$bat/uevent | cut -d= -f2)
	    design=$(grep 'POWER_SUPPLY_ENERGY_FULL_DESIGN=' /sys/class/power_supply/$bat/uevent | cut -d= -f2)
	    cycles=$(grep 'POWER_SUPPLY_CYCLE_COUNT=' /sys/class/power_supply/$bat/uevent | cut -d= -f2)
	    loss=$(( design - full ))
}

print_values () {
	awk -v capacity=$capacity -v full=$full -v design=$design -v loss=$loss -v cycles=$cycles '
		
		    BEGIN {
		        o = "\033[0;33m"
		        r = "\033[0m"
		        printf o "POWER_SUPPLY_CAPACITY"            r "=%.0f%\n",                          capacity
		        printf o "POWER_SUPPLY_ENERGY_FULL_DESIGN"  r "=%.2f Wh\n",                         design/1000000
		        printf o "POWER_SUPPLY_ENERGY_FULL"         r "=%.2f Wh\n",                         full/1000000
		        printf o "POWER_SUPPLY_ENERGY_LOSS"         r "=%.2f Wh (%d%% degradation)\n",      loss/1000000, loss*100/design
		        printf o "POWER_SUPPLY_CYCLE_COUNT"         r "=%d\n",                              cycles
		    }'
}

main () {
	echo
	for bat in BAT0 BAT1; do
	    echo "$bat:"
		get_values
		print_values
	    echo
	done
}

main
